---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Introduction"
      solveButton: false
    - name: module-02
      label: "Import a project to Event-Driven Ansible"
      solveButton: false
    - name: module-03
      label: "Rulebook Activations"
      solveButton: false
    - name: module-04
      label: "Observe some events"
      solveButton: false
    - name: module-05
      label: "Event Streams"
      solveButton: false
    - name: module-06
      label: "Open challenge"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
    modules:
      - module-01
      - module-02
      - module-03
      - module-04
      - module-05
      - module-06    
    external: false
  - name: ">_ Terminal"
    url: /wetty
    modules:
      - module-01
  - name: Gitea
    url: https://gitea-${guid}.${domain}/
    modules:
      - module-02
      - module-03
      - module-04
      - module-05
      - module-06
  - name: Prometheus
    url: https://podman-${guid}.${domain}:9090/
    modules:
      - module-04
      - module-05
      - module-06
  - name: ">_ RHEL1"
    url: /wetty_rhel-1
    modules:
      - module-04
      - module-05
      - module-06
  - name: ">_ RHEL2"
    url: /wetty_rhel-2
    modules:
      - module-04
      - module-05
      - module-06
  - name: ">_ Podman"
    url: /wetty_podman
    modules:
      - module-05
      - module-06
  
  # - name: Windows RDP
  #   url: https://windows-ironrdp-${guid}.${domain}/
  #   external: false
  # - name: ">_ control"
  #   url: /wetty
  # - name: ">_ node01"
  #   url: /wetty_node01
  # - name: ">_ node02"
  #   url: /wetty_node02
  # - name: ">_ node03"
  #   url: /wetty_node03
  # - name: Cloud (PoC)
  #   url: /cloud
