---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Introduction"
      solveButton: false
    - name: module-02
      label: "Import a project to Event-Driven Ansible"
      solveButton: false
    - name: module-03
      label: "Rulebook Activations"
      solveButton: false
    - name: module-04
      label: "Observe some events"
      solveButton: false
    - name: module-05
      label: "Event Streams"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
    modules:
      - module-01
      - module-02
      - module-03
      - module-04
      - module-05
    external: false
  - name: ">_ Terminal"
    url: /wetty
    modules:
      - module-01
  - name: Gitea
    url: https://podman-gitea-${guid}.${domain}/
    modules:
      - module-02
      - module-03
      - module-04
      - module-05
    external: false
  - name: Prometheus
    url: https://prometheus-${guid}.${domain}/
    modules:
      - module-04
      - module-05
  - name: ">_ RHEL1"
    url: /wetty_rhel-1
    modules:
      - module-04
      - module-05
  - name: ">_ RHEL2"
    url: /wetty_rhel-2
    modules:
      - module-04
      - module-05
  - name: ">_ Podman"
    url: /wetty_podman
    modules:
      - module-05
